### ISSUE TITLE
Execution using Radical Pilot Titan ORTE Configuration

### ISSUE THREAD

**Issue by jrossyra** [jrossyra/admdrpruns#1]
We had the resource config selecting `titan_aprun`, we want to go with `titan_orte`. A number of issues are posted related to this, updating soon with links and further description.

**Comment by vivek-bala** [comment]
One point I want to mention/remind (in case you already have these in the pending links, please ignore):

If your task is MPI based, you may need to recompile it with the openmpi that RP uses to enable ORTE. Non-MPI tasks should be able to run as is with ORTE. I think you mentioned you would be testing the intergration with null workload initially, but you might want to consider the recompilation simultaneously.

**Comment by mturilli** [comment]
Depends on https://github.com/radical-cybertools/radical.pilot/issues/1538
