### ISSUE TITLE
Consolidating RP stack for integration

### ISSUE THREAD

**Issue by mturilli** [jrossyra/admdrpruns#3]
Opened a ticket at: https://github.com/radical-cybertools/radical.pilot/issues/1545

**Comment by mturilli** [comment]
Needs to support MongoDB 3.*; GPU on Titan

**Comment by itomaldonado** [comment]
Support for MongoDB 3.* is added on `radical.pilot@issue/1418` but I will merge the changes ones we have the branch specific to this project.
